spring:
  application:
    name: gateway
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  cloud:
    discovery:
      enabled: true
    gateway:
      mvc:
        routes:
          - id: authorization-server
            uri: lb://AUTHORIZATIONSERVER
            predicates:
              - Path=/authorization/**
          - id: user-service
            uri: lb://USERSERVICE
            predicates:
              - Path=/user/**
          - id: ticket-service
            uri: lb://TICKETSERVICE
            predicates:
              - Path=/ticket/**
          - id: notification-service
            uri: lb://NOTIFICATIONSERVICE
            predicates:
              - Path=/notification/**
#            filters:
#              -name: RequestRateLimiter
#              args:
#                rate-limiter: "#{customRateLimiter}"
#                key-resolver: "#{customKeyResolver}"

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${USER_NAME}:${PASSWORD}@localhost:5002/eureka/

server:
  port: ${SERVER_PORT}

jwks:
  uri: ${JWKS_URI}